### ISSUE TITLE
Search not working in Map Sharing Settings

### ISSUE THREAD

**Issue by jrhillma** [goryn-clade/pathfinder-containers#73]
As title. New instance of Pathfinder (thanks for the docker image and clear instructions!), authorized a user, created a "Private" map. Tried to add another user to the map in "Sharing" but search only returns "No results found." Tried adding an entire corp, same result. Corporation search works when editing a Structure. Search also works when adding a system to the Routes panel.

**Comment by nefyodovve** [comment]
@jrhillma 

You are talking about 'session sharing' feature [added](https://github.com/goryn-clade/pathfinder/releases/tag/v2.1.1) in goryn's repo , or original 'share' feature?

Session sharing is for your alt who is not in main's corp. It works only on your computer because credentials stored in your browser, it will not work on other browser on other computer.

Original share feature is for true sharing with others, and another person should allow sharing in his account settings. This is done for security reasons, to prevent adding any character to map and hunt him down with map's tracking ability. Manual for this feature exists in topbar on main page of the app (button 'Manual' -> 'Share' tab). Account settings are in the 'Main' menu on the left in map.

**Comment by jrhillma** [comment]
@nefyodovve Thanks for pointing me in the right direction. I should have RTFM first. I've used public Pathfinder quite a bit and never seen those options. Perhaps they're on by default in the maps I've been given access to. At any rate, issue is resolved, so closing. Again, greatly appreciate the help!
